<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>owl</string>
	</array>
	<key>name</key>
	<string>Owl</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>#</string>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment.line.number-sign.owl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(if|while|for|return)\b</string>
			<key>name</key>
			<string>keyword.control.owl</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.owl</string>
	<key>uuid</key>
	<string>E6847AED-A1EC-439D-85EC-1AE81268CA35</string>
</dict>
</plist>
